### PR TITLE
change statucode for delete file when file not found.

### PR DESCRIPTION
**Pull request by princeparmar**
Signed-off-by: Pradip Parmar <pradip@alfa-creator.com>

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR
Issue https://github.com/0chain/zboxcli/issues/99
Associated PRs (Link as appropriate):
- zbox: https://github.com/0chain/zboxcli/pull/181
- zwalelet:
- gosdk: https://github.com/0chain/gosdk/pull/396
- 0chain:
- system_test:

### CODE REVIEW

**Review by cnlangzi — APPROVED** [review]
LGTM

**Comment by cnlangzi** [comment]
@princeparmar please don't forget to update gosdk/zbox for this change.

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feature/99-statuscode-204-for-file-not-found  |
| zboxcli  | feature/99-statuscode-204-for-file-not-found  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/99-statuscode-204-for-file-not-found  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feature/99-statuscode-204-for-file-not-found  |
| zboxcli  | feature/99-statuscode-204-for-file-not-found  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/99-statuscode-204-for-file-not-found  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Pull request merged**
