### PR TITLE
delete file query update.

### LINKED ISSUE #448: allocated size should be incorrect on _stats
In general , correct stats should be like
- AllocatedSize >= UsedSize 
- ActualDiskUsage == FilesSize

Screen Shot 2021-12-02 at 07 06 58

### LINKED ISSUE #517: file/thunmbnail are not deleted from disk after `zbox delete`
physical path is generated by allocation id and content hash.A physical path may be referenced by multiple reference_objects.  
- references should be checked before file is deleted from disk. 
- stale file should be deleted if a file is changed by `zbox update`

### LINKED ISSUE #543: stale file/thumbnail should be deleted on ./zbox update
if a file is updated, the physical file path on disk will be changed too. Because the path is generated based on allocation id and content hash. so stale file/thumbnail should be deleted from disk on commitwrite stage.

related to https://github.com/0chain/blobber/issues/517

### PR DESCRIPTION
**Pull request by princeparmar**
Signed-off-by: Pradip Parmar <pradip@alfa-creator.com>

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
- zbox:
- zwalelet:
- gosdk:
- 0chain:
- system_test:

### CODE REVIEW

**Review by cnlangzi — CHANGES_REQUESTED** [review]
delete thumbnail if it has.

its thumbnail should be deleted too if a file is deleted.

please check `nf.ContentHash` if it includes `file content hash` and `thumbnail content hash`. @princeparmar

**Review by cnlangzi — DISMISSED** [review]
It seems works.

**Comment by cnlangzi** [comment]
@princeparmar  thumbnail content hash is not loaded on https://github.com/0chain/blobber/blob/6b4a6991892e395fb610cf4eec47fa7898f59322/code/go/0chain.net/blobbercore/reference/object.go#L64

**Review by cnlangzi — APPROVED** [review]

**Comment by cnlangzi** [comment]
@princeparmar  please fix https://github.com/0chain/blobber/issues/543 too

**Comment by princeparmar** [comment]
@cnlangzi i have added https://github.com/0chain/blobber/issues/543 related fix in this one.

**Review by cnlangzi — APPROVED** [review]
LGTM

**Pull request merged**
