### PR TITLE
fix(hash): updated sha1 with sha256 for file hash

### PR DESCRIPTION
**Pull request by cnlangzi**
Tasks to complete before merging PR:
- [x]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [x]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [x]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
- zbox: https://github.com/0chain/zboxcli/pull/159
- zwalelet:
- gosdk: https://github.com/0chain/gosdk/pull/363
- 0chain:
- system_test: https://github.com/0chain/system_test/pull/173

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/update_sha1_with_sha256_for_file_hash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/update_sha1_with_sha256_for_file_hash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/fix_thumbnail_remove_issue  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/update_sha1_with_sha256_for_file_hash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/update_sha1_with_sha256_for_file_hash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/fix_thumbnail_assertion  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/update_sha1_with_sha256_for_file_hash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/update_sha1_with_sha256_for_file_hash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/update_sha1_with_sha256_for_file_hash  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/update_sha1_with_sha256_for_file_hash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/fix_thumbnail_assertion  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/update_sha1_with_sha256_for_file_hash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/update_sha1_with_sha256_for_file_hash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/fix_thumbnail_assertion  |
| gosdk  | fix/update_sha1_with_sha256_for_file_hash  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/update_sha1_with_sha256_for_file_hash  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by ssardana96 — APPROVED** [review]

**Comment by ssardana96** [comment]
should be good to merge once all checks are done

**Review by kushthedude — DISMISSED** [review]
Dont we make this hash changes at other places too in gosdk & zbox where we are actually passing & using it? This can break the file related endpoints, as can be seen from system_tests run

**Comment by cnlangzi** [comment]
> Dont we make this hash changes at other places too in gosdk & zbox where we are actually passing & using it? This can break the file related endpoints, as can be seen from system_tests run

yes. check related links on PR's description

**Comment by cnlangzi** [comment]
@kushthedude  PR seems is blocked by your `requested changes`. but there is no any conversation is opened. It is impossible to merge it now. could you help to check it again?

**Pull request merged**
