### PR TITLE
Feat/partial delete suppport

### LINKED ISSUE #385: TBD: When deleting folder - it deletes wrong hash
After deleting second folder I got response is
12:52
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:10.688198 deleteworker.go:74: http://dev.0chain.net:31305 /Second Folder deleted.
    0box-sdk: [INFO]   2021/10/12 05:48:10.689572 deleteworker.go:74: http://dev.0chain.net:31304 /Second Folder deleted.
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:10.689572 deleteworker.go:74: http://dev.0chain.net:31306 /Second Folder deleted.
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:10.783995 deleteworker.go:74: http://dev.0chain.net:31302 /Second Folder deleted.
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:10.784814 commitworker.go:102: received a commit request
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:10.784813 commitworker.go:102: received a commit request
    0box-sdk: [INFO]   2021/10/12 05:48:10.784859 commitworker.go:102: received a commit request
    0box-sdk: [INFO]   2021/10/12 05:48:10.784914 commitworker.go:102: received a commit request
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.266665 commitworker.go:163: Allocation root from latest writemarker mismatch. Expected: ac7cfc6703ffb5e50fa8da51a44ebaa747e8efc4caa200d1d5c3b638dcbb9749 got: 6dc6bb68d69a5be5a188e316dfe7e08f49f48a4655d6a95fec5606090df32b2d
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.269443 commitworker.go:243: Committing to blobber.http://dev.0chain.net:31302
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.300432 commitworker.go:163: Allocation root from latest writemarker mismatch. Expected: 77edf8f48184362d65bbe00bfe50d17cdac4f422038ef74d05d11b17105227c2 got: d4f70374b966bf6d617035877a62d6a46eca977882b8e0f77911ea9fb6709a9b
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.302854 commitworker.go:243: Committing to blobber.http://dev.0chain.net:31306
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.377038 commitworker.go:163: Allocation root from latest writemarker mismatch. Expected: 4d7d08ac276b2948f436b23e02aedcf0c9ccf0f0c2cae4b03cd9a5650a676099 got: f3eaecf11599b2e09f3254a9de5f5649a46af1bdcbf22449a5e83a9f9b6020cd
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.378876 commitworker.go:243: Committing to blobber.http://dev.0chain.net:31304
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.470417 commitworker.go:163: Allocation root from latest writemarker mismatch. Expected: 1419cb33c7619cd14297a1df1673f460c8bf5cccbe5301a193cec1061866f0b0 got: b7463a72e9d9ddaf1eae2c4625b105d1c84bc1e893caf2378a4a704eed9fa5c2
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.474017 commitworker.go:243: Committing to blobber.http://dev.0chain.net:31305
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.601274 commitworker.go:251: http://dev.0chain.net:31306DYcWs2QvumbxtzYDWYPobV committed
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.612712 commitworker.go:251: http://dev.0chain.net:31302DYcWs2QvumbxtzYDWYPobV committed
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.749807 commitworker.go:251: http://dev.0chain.net:31305DYcWs2QvumbxtzYDWYPobV committed
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.887243 commitworker.go:251: http://dev.0chain.net:31304DYcWs2QvumbxtzYDWYPobV committed
E/GoLog: 0box-sdk: [INFO]   2021/10/12 05:48:11.888371 deleteworker.go:157: Commit successhttp://dev.0chain.net:31302
    0box-sdk: [INFO]   2021/10/12 05:48:11.888581 deleteworker.go:157: Commit successhttp://dev.0chain.net:31304
    0box-sdk: [INFO]   2021/10/12 05:48:11.888683 deleteworker.go:157: Commit successhttp://dev.0chain.net:31305
    0box-sdk: [INFO]   2021/10/12 05:48:11.888764 deleteworker.go:157: Commit successhttp://dev.0chain.net:31306
12:53
I got below response when I call listDir (edited) 
12:53
[{"name":"IMG-20211012-WA0000.jpg","path":"\/IMG-20211012-WA0000.jpg","type":"f","size":247788,"hash":"366666303b44c964164153e105a712b9a13ff4524cb5f0262e4617d67c9f73e1","mimetype":"image\/jpeg","num_blocks":4,"lookup_hash":"fc9d5a5b8886cce80f9ac8110f8cc50e2e24ada42c90d558a9fcb7718770595a","encryption_key":"","attributes":{},"actual_size":123894,"actual_num_blocks":1,"created_at":"2021-10-12T05:41:53.325123Z","updated_at":"2021-10-12T05:48:12.325183Z","list":null},{"name":"Second Folder","path":"\/Second Folder","type":"d","size":8,"num_blocks":8,"lookup_hash":"76208c8a2bf9d4d43db3030100c7588727f8d8573a8b1450535a7d016fa30ddf","encryption_key":"","attributes":{},"actual_size":0,"actual_num_blocks":0,"created_at":"2021-10-12T05:47:39.958681Z","updated_at":"2021-10-12T05:47:39.958681Z","list":null}]
12:53
First Folder deleted but I requested to delete second Folder (edited)

### LINKED ISSUE #556: status code 204 should be returned if file is not found in disk
check io err `no such file or directory`. status code 204 should be returned like we did on https://github.com/0chain/zboxcli/issues/99

### PR DESCRIPTION
**Pull request by cnlangzi**
### Changes
- return 404 instead of 400 if file is not found 

### Fixes
- removed unused error

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber: https://github.com/0chain/blobber/pull/626
- system_test: https://github.com/0chain/system_test/pull/234
- zboxcli: https://github.com/0chain/zboxcli/pull/208
- gosdk: https://github.com/0chain/gosdk/pull/427

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/partial-delete-suppport  |
| zboxcli  | feat/partial-delete-suppport  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feat/partial-delete-suppport  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feat/partial-delete-suppport  |
| gosdk  | feat/partial-delete-suppport  |
| zboxcli  | feat/partial-delete-suppport  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feat/partial-delete-suppport  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feat/partial-delete-suppport  |
| gosdk  | feat/partial-delete-suppport  |
| zboxcli  | feat/partial-delete-suppport  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feat/partial-delete-suppport  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

**Review by peterlimg — APPROVED** [review]
lgtm

**Pull request merged**
