### PR TITLE
upload file issue

### PR DESCRIPTION
**Pull request by boddumanohar**
### Changes

This PR fixes 2 issues:

* `too less sharders to confirm` error --> https://github.com/0chain/blobber/issues/860
* challenge timeout errors. This is fixed by removing the usage of `loadTodoChallenges`. Due to the row scan operations, `loadTodoChallenges` is taking a lot of time and also this this function is not required, as we can send to the `toProcess` channel immediately in syncChallenges function

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by lpoli — CHANGES_REQUESTED** [review]
This PR has is same as what it had been. I don't think it has solved database lag issue.
We can make it work the following way:
1. Create goroutines that continuously listens to the the channel.
2. Upon syncing challenges, feed challenges to the channel.
3. There can be multiple number of worker goroutines that process these challenges. These challenges will be listened in above step 1 and it will feed challenge to the worker.
4. Check validator response. Commit challenge if it is validated and within cct. 
5. Store challenge in database regardless of success or failure.

**Comment by boddumanohar** [comment]
The performance impact was in [loadTodoChallenges](https://github.com/0chain/blobber/pull/858/files#diff-641a3515d6a0f82f27055091ce61d4b8e1992e958c14749dd2baf15bef226402L351-L408) which takes challenges from DB. 

Instead of taking challenges from DB, I have created a channel and pushing it to challenge here:

https://github.com/0chain/blobber/blob/ad57c1a9242089bcf1cfbd8cbd19dbccd3eca9e2/code/go/0chain.net/blobbercore/challenge/challenge.go#L108-L112

and I am receiving from the channel in `challengeProcessor`

https://github.com/0chain/blobber/blob/ed593afde9b88c5992df6299e8f648bfe1bd88e9/code/go/0chain.net/blobbercore/challenge/worker.go#L59

**Comment by boddumanohar** [comment]
I understand your suggestion, will be making the changes accordingly. Thanks.

**Comment by boddumanohar** [comment]
This PR doesn't fix the actual issue. Actually reason is documented here:
https://0chain.slack.com/archives/GREHVKQKS/p1666878974939929

https://github.com/0chain/blobber/blob/aa49a30b53415f01e00b36c6e7f814d265ed35dc/code/go/0chain.net/blobbercore/filestore/storage.go#L386
this the is the piece of code which is taking time:
```
errWrite := fixedMT.Write(dataBytes, chunkIndex)
```
this line takes somewhere  1ms - 1.459589923s and we do this for 3711 times in a for loop.
On average this entire for loop takes 4-7 mins

**Pull request closed without merging**
