### PR TITLE
- fix/challenges

### LINKED ISSUE #641: Challenges not getting stored in db
- Blobber has challenges generated by chain, but not getting stored in blobber db.
- On debugging, found the issue while [decoding /openchallenges response](https://github.com/0chain/blobber/blob/9d6fe7b078eb40d7759b9e70f06ee8e977e1e4ca/code/go/0chain.net/blobbercore/challenge/challenge.go#L49)

### PR DESCRIPTION
**Pull request by ssardana08**
### Changes
- fixed Issue with /getchallenge response unmarshalling

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain: https://github.com/0chain/0chain/pull/1189
- gosdk:
- system_test: https://github.com/0chain/system_test/pull/248
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by cnlangzi — APPROVED** [review]
LGTM

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/challenges  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/challenges  |
| blobber  | fix/challenges  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

**Comment by cnlangzi** [comment]
@sum-it08  I am working on this challenge issue for latest bbr. so just leave it with me , thanks.

**Comment by peterlimg** [comment]
@cnlangzi @sum-it08 please describe the problem that the PR is going to resolve. Reviewers need to know what this PR for and what issues it will fix.

**Comment by ssardana08** [comment]
@peterlimg I've added changes in PR description now.

**Comment by ssardana08** [comment]
> @sum-it08 I am working on this challenge issue for latest bbr. so just leave it with me , thanks.

@cnlangzi didn't get - what more changes needed?

**Comment by cnlangzi** [comment]
@sum-it08  getting more errors on challenge, please check it on https://0chain.slack.com/archives/C020E8HA8TE/p1651723437262479?thread_ts=1650570070.706369&cid=C020E8HA8TE

**Pull request merged**
