### PR TITLE
Changing gosdk to v0.0.0

### PR DESCRIPTION
**Pull request by moldis**

### CODE REVIEW

**Review by kushthedude — CHANGES_REQUESTED** [review]
We don't release 0.0.0

**Comment by moldis** [comment]
> We don't release 0.0.0

Since last gosdk release, it will be released together with actuall release, i.e. v0.0.0 and v1... etc.

**Comment by kushthedude** [comment]
> Since last gosdk release, it will be released together with actuall release, i.e. v0.0.0 and v1... etc.

That;s not how releases works, refer this please https://semver.org/

**Review by kushthedude — CHANGES_REQUESTED** [review]
This should be discussed before merging, lets not add more tech-debt to the project. We already have a lot to tackle once we are on mainnet.

**Pull request merged**
