### PR TITLE
Add path in thumbnail hash

### PR DESCRIPTION
**Pull request by Hitenjain14**
### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk: https://github.com/0chain/gosdk/pull/1013
- system_test:
- zboxcli: https://github.com/0chain/zboxcli/pull/450
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | fix/path-hash  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/add-child  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | fix/path-hash  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/add-child  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | fix/thumb-hash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/add-child  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/thumb-hash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/add-child  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | fix/path-hash  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/allow-empty-root  |
| blobber  | fix/add-child  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | fix/path-hash  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | fix/allow-empty-root  |
| blobber  | fix/add-child  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | fix/thumb-hash  |
| zwalletcli  | staging  |
| 0chain  | fix/allow-empty-root  |
| blobber  | fix/add-child  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | fix/thumb-hash  |
| zwalletcli  | staging  |
| 0chain  | fix/allow-empty-root  |
| blobber  | fix/add-child  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | fix/path-hash  |
| zboxcli  | fix/thumb-hash  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/add-child  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by Hitenjain14** [comment]
Recent system test run https://github.com/0chain/system_test/actions/runs/5389253755/jobs/9786972827

**Pull request merged**
