### PR TITLE
fix(devops): fixed gcc build issue on alpine

### PR DESCRIPTION
**Pull request by cnlangzi**
### Fixes
- fixed gcc build issue on alpine

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by Kishan-Dhakan** [comment]
Please check it
image

**Comment by cnlangzi** [comment]
@Kishan-Dhakan  failed on zs3server tests
```
=== Failed
=== FAIL: tests/api_tests TestZs3ServerOperations/CreateBucket_should_return_200_when_all_the_parameters_are_correct (45.00s)
=== FAIL: tests/api_tests TestZs3ServerOperations/CreateBucket_should_not_return_error_when_bucket_name_already_exist (45.00s)
=== FAIL: tests/api_tests TestZs3ServerOperations/ListBucket_should_return_200_all_the_parameter_are_correct (30.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations/ListObjects_should_return_200_all_the_parameter_are_correct (30.03s)
=== FAIL: tests/api_tests TestZs3ServerOperations/PutObjects_should_return_200_all_the_parameter_are_correct (45.00s)
=== FAIL: tests/api_tests TestZs3ServerOperations/GetObjects_should_return_200_all_the_parameter_are_correct (30.03s)
=== FAIL: tests/api_tests TestZs3ServerOperations/RemoveObject_should_return_200_all_the_parameter_are_correct (45.00s)
=== FAIL: tests/api_tests TestZs3ServerOperations/RemoveObject_should_not_return_error_if_object_doen't_exist (30.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations/zs3_server_should_return_500_when_the_credentials_aren't_correct (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (300.10s)
=== FAIL: tests/api_tests TestZs3ServerOperations/CreateBucket_should_return_200_when_all_the_parameters_are_correct (re-run 1) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 1) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations/CreateBucket_should_not_return_error_when_bucket_name_already_exist (re-run 1) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 1) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations/ListBucket_should_return_200_all_the_parameter_are_correct (re-run 1) (30.02s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 1) (30.02s)
=== FAIL: tests/api_tests TestZs3ServerOperations/ListObjects_should_return_200_all_the_parameter_are_correct (re-run 1) (30.04s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 1) (30.04s)
=== FAIL: tests/api_tests TestZs3ServerOperations/PutObjects_should_return_200_all_the_parameter_are_correct (re-run 1) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 1) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations/GetObjects_should_return_200_all_the_parameter_are_correct (re-run 1) (30.04s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 1) (30.04s)
=== FAIL: tests/api_tests TestZs3ServerOperations/RemoveObject_should_return_200_all_the_parameter_are_correct (re-run 1) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 1) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations/RemoveObject_should_not_return_error_if_object_doen't_exist (re-run 1) (30.03s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 1) (30.03s)
=== FAIL: tests/api_tests TestZs3ServerOperations/zs3_server_should_return_500_when_the_credentials_aren't_correct (re-run 1) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 1) (0.00s)
=== FAIL: tests/api_tests TestZs3ServerOperations/CreateBucket_should_return_200_when_all_the_parameters_are_correct (re-run 2) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 2) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations/CreateBucket_should_not_return_error_when_bucket_name_already_exist (re-run 2) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 2) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations/ListBucket_should_return_200_all_the_parameter_are_correct (re-run 2) (30.05s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 2) (30.05s)
=== FAIL: tests/api_tests TestZs3ServerOperations/ListObjects_should_return_200_all_the_parameter_are_correct (re-run 2) (30.04s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 2) (30.04s)
=== FAIL: tests/api_tests TestZs3ServerOperations/PutObjects_should_return_200_all_the_parameter_are_correct (re-run 2) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 2) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations/GetObjects_should_return_200_all_the_parameter_are_correct (re-run 2) (30.02s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 2) (30.03s)
=== FAIL: tests/api_tests TestZs3ServerOperations/RemoveObject_should_return_200_all_the_parameter_are_correct (re-run 2) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 2) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations/RemoveObject_should_not_return_error_if_object_doen't_exist (re-run 2) (30.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 2) (30.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations/zs3_server_should_return_500_when_the_credentials_aren't_correct (re-run 2) (45.01s)
=== FAIL: tests/api_tests TestZs3ServerOperations (re-run 2) (0.00s)
```

**Review by peterlimg — APPROVED** [review]
LGTM

**Comment by Kishan-Dhakan** [comment]
@cnlangzi please check https://0chain.slack.com/archives/C0276HLCN5S/p1686175147503839

**Pull request merged**
