### PR TITLE
fix(allocation):update NewConnectionId with zboxutil.NewConnectionId

### PR DESCRIPTION
**Pull request by cnlangzi**
fixed https://github.com/0chain/blobber/issues/288

### CODE REVIEW

**Review by kushthedude — CHANGES_REQUESTED** [review]
zboxutil generates the number in the same way too https://github.com/0chain/gosdk/blob/826e79c0eb2030c6ba1ada3f0aa7928c67e5d590/zboxcore/zboxutil/util.go#L85

**Comment by cnlangzi** [comment]
> zboxutil generates the number in the same way too https://github.com/0chain/gosdk/blob/826e79c0eb2030c6ba1ada3f0aa7928c67e5d590/zboxcore/zboxutil/util.go#L85

it is fixed on https://github.com/0chain/gosdk/pull/179

**Comment by kushthedude** [comment]
> > zboxutil generates the number in the same way too https://github.com/0chain/gosdk/blob/826e79c0eb2030c6ba1ada3f0aa7928c67e5d590/zboxcore/zboxutil/util.go#L85
> 
> it is fixed on [0chain/gosdk#179](https://github.com/0chain/gosdk/pull/179)

merge the PR, bump the gosdk, change the go.mod in blobber to use the latest sdk then the following PR should be merged else it will refer to same code.

**Review by moldis — APPROVED** [review]
Looks good

**Comment by cnlangzi** [comment]
> > > zboxutil generates the number in the same way too https://github.com/0chain/gosdk/blob/826e79c0eb2030c6ba1ada3f0aa7928c67e5d590/zboxcore/zboxutil/util.go#L85
> > 
> > 
> > it is fixed on [0chain/gosdk#179](https://github.com/0chain/gosdk/pull/179)
> 
> merge the PR, bump the gosdk, change the go.mod in blobber to use the latest sdk then the following PR should be merged else it will refer to same code.

done

**Pull request merged**
