### PR TITLE
Duplicate WM

### LINKED ISSUE #1050: Duplicate Writemarker
We are seeing this error when running  create Directory tests. 
Need to investigate this further to know when such case can happen and fix it.

Example Run - [Manual system test](https://github.com/0chain/system_test/actions/runs/4841106530/jobs/8627191179#step:7:1958)

### PR DESCRIPTION
**Pull request by Hitenjain14**
### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk: https://github.com/0chain/gosdk/pull/938
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | two-phase-timestamp  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | test-createdir  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/create-dir  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | two-phase-timestamp  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | test-createdir  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/create-dir  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | two-phase-timestamp  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | test-createdir  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Review by lpoli — APPROVED** [review]

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/create-dir  |
| gosdk  | two-phase-timestamp  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | test-createdir  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | two-phase-timestamp  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | test-createdir  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | fix/create-dir  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | two-phase-timestamp  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | test-createdir  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Pull request merged**
