### PR TITLE
packager logger for filtering logs

### PR DESCRIPTION
**Pull request by PratikDhanave**
### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by cnlangzi** [comment]
@PratikDhanave please get tests passed first.

**Comment by lpoli** [comment]
@PratikDhanave 
Firstly, The logger that you wrote is not necessary. There is already `core/logging` which has all the necessary logging levels.
Secondly, You have not done anything that was raised in issue https://github.com/0chain/blobber/issues/290. What was required was to log critical errors, any thing that would be required while debugging, etc.

**Comment by peterlimg** [comment]
@PratikDhanave please check the `core/logging` as @lpoli mentioned. @cnlangzi @lpoli please guide @PratikDhanave what need to do.

**Comment by PratikDhanave** [comment]
@peterlimg @lpoli @cnlangzi I will update the pull request  to log critical errors.

**Pull request closed without merging**
