### PR TITLE
Empty ID

### LINKED ISSUE #1045: FileID becomes null after update operation
1. Update any file in blobber; see its id in the `reference_objects` table. 

Note: It may affect the writemarker calculation in gosdk.

### PR DESCRIPTION
**Pull request by Hitenjain14**
### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk: https://github.com/0chain/gosdk/pull/954
- system_test:
- zboxcli: https://github.com/0chain/zboxcli/pull/430
- zwalletcli:
- Other: ...

### CODE REVIEW

**Review by lpoli — APPROVED** [review]

**Review by dabasov — APPROVED** [review]
lgtm

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/empty-id  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/empty-id  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix-empty-id  |
| gosdk  | fix/empty-id  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix-empty-id  |
| gosdk  | fix/empty-id  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix-empty-id  |
| gosdk  | fix/empty-id  |
| zboxcli  | fix/empty-id  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/empty-id  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
