### PR TITLE
Decouple readmarker handling from downloading process

### LINKED ISSUE #876: Optimize upload and download of large files
https://blob-chart.zus.network/?path=instance1-test3&id=450000x8-EC51

### PR DESCRIPTION
**Pull request by din-mukhammed**
### Changes
For https://github.com/0chain/gosdk/issues/876
[PR#878](https://github.com/0chain/gosdk/pull/878)

Implements quota for downloads. Client needs to submit readmarker before downloading data to create quota. 

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk: https://github.com/0chain/gosdk/pull/878
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

### CODE REVIEW

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by din-mukhammed** [comment]
go.mod is pointing to gosdk branch ["optimize-download-upload"](https://github.com/0chain/gosdk/pull/878). [PR#878](https://github.com/0chain/gosdk/pull/878) needs to be merged first, then go.mod needs to be reverted here.

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | optimize-download-fix  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | optimize-download-fix  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Comment by service-0chain** [comment]
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | optimize-download-fix  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

**Review by dabasov — APPROVED** [review]
lgtm

**Pull request merged**
